version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
    labels:
      - "dependencies"
    commit-message:
      prefix: "go.mod"
      include: scope
