// Code generated by MockGen. DO NOT EDIT.
// Source: backupunit.go

// Package mock_resources is a generated GoMock package.
package mock_resources

import (
	"github.com/ionos-cloud/ionosctl/pkg/resources/v6"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBackupUnitsService is a mock of BackupUnitsService interface.
type MockBackupUnitsService struct {
	ctrl     *gomock.Controller
	recorder *MockBackupUnitsServiceMockRecorder
}

// MockBackupUnitsServiceMockRecorder is the mock recorder for MockBackupUnitsService.
type MockBackupUnitsServiceMockRecorder struct {
	mock *MockBackupUnitsService
}

// NewMockBackupUnitsService creates a new mock instance.
func NewMockBackupUnitsService(ctrl *gomock.Controller) *MockBackupUnitsService {
	mock := &MockBackupUnitsService{ctrl: ctrl}
	mock.recorder = &MockBackupUnitsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackupUnitsService) EXPECT() *MockBackupUnitsServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBackupUnitsService) Create(u v6.BackupUnit) (*v6.BackupUnit, *v6.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", u)
	ret0, _ := ret[0].(*v6.BackupUnit)
	ret1, _ := ret[1].(*v6.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *MockBackupUnitsServiceMockRecorder) Create(u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBackupUnitsService)(nil).Create), u)
}

// Delete mocks base method.
func (m *MockBackupUnitsService) Delete(backupUnitId string) (*v6.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", backupUnitId)
	ret0, _ := ret[0].(*v6.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockBackupUnitsServiceMockRecorder) Delete(backupUnitId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBackupUnitsService)(nil).Delete), backupUnitId)
}

// Get mocks base method.
func (m *MockBackupUnitsService) Get(backupUnitId string) (*v6.BackupUnit, *v6.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", backupUnitId)
	ret0, _ := ret[0].(*v6.BackupUnit)
	ret1, _ := ret[1].(*v6.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockBackupUnitsServiceMockRecorder) Get(backupUnitId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBackupUnitsService)(nil).Get), backupUnitId)
}

// GetSsoUrl mocks base method.
func (m *MockBackupUnitsService) GetSsoUrl(backupUnitId string) (*v6.BackupUnitSSO, *v6.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSsoUrl", backupUnitId)
	ret0, _ := ret[0].(*v6.BackupUnitSSO)
	ret1, _ := ret[1].(*v6.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSsoUrl indicates an expected call of GetSsoUrl.
func (mr *MockBackupUnitsServiceMockRecorder) GetSsoUrl(backupUnitId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSsoUrl", reflect.TypeOf((*MockBackupUnitsService)(nil).GetSsoUrl), backupUnitId)
}

// List mocks base method.
func (m *MockBackupUnitsService) List() (v6.BackupUnits, *v6.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].(v6.BackupUnits)
	ret1, _ := ret[1].(*v6.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockBackupUnitsServiceMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBackupUnitsService)(nil).List))
}

// Update mocks base method.
func (m *MockBackupUnitsService) Update(backupUnitId string, input v6.BackupUnitProperties) (*v6.BackupUnit, *v6.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", backupUnitId, input)
	ret0, _ := ret[0].(*v6.BackupUnit)
	ret1, _ := ret[1].(*v6.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Update indicates an expected call of Update.
func (mr *MockBackupUnitsServiceMockRecorder) Update(backupUnitId, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBackupUnitsService)(nil).Update), backupUnitId, input)
}
