project_name: ionosctl

before:
  hooks:
    - go mod tidy
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
      - -mod=vendor
    ldflags:
      - "-X github.com/ionos-cloud/ionosctl/commands.Major={{ .Major }}"
      - "-X github.com/ionos-cloud/ionosctl/commands.Minor={{ .Minor }}"
      - "-X github.com/ionos-cloud/ionosctl/commands.Patch={{ .Patch }}"
      - "-X github.com/ionos-cloud/ionosctl/commands.Label=release"
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: '{{ .ProjectName }}'
archives:
  - name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    files: [include-only-the-binary*]
    wrap_in_directory: false
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-SHA256SUMS'
  algorithm: sha256
release:
# If you want to manually examine the release before its live, uncomment this line:
# draft: true
changelog:
  skip: false
