project_name: ionosctl

before:
  hooks:
    - go mod tidy
builds:
  - 
    id: ionosctl
    main: ./main.go
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
      - -mod=vendor
    ldflags:
      - "-X github.com/ionos-cloud/ionosctl/commands.Version={{ .Version }}"
      - "-X github.com/ionos-cloud/ionosctl/commands.Label=release"
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: '{{ .ProjectName }}'
archives:
  - 
    id: ionosctl
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    files: [include-only-the-binary*]
    wrap_in_directory: false
brews:
  -
    name: ionosctl
    ids:
      - ionosctl
    tap: 
      owner: ionos-cloud
      name: homebrew-ionos-cloud
    folder: Formula
    goarm: "7"
    homepage: https://github.com/ionos-cloud/ionosctl
    dependencies:
      - name: go
        type: optional
    install: |-
      bin.install "ionosctl"
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-SHA256SUMS'
  algorithm: sha256
release:
# If you want to manually examine the release before its live, uncomment this line:
# draft: true
changelog:
  skip: false
