project_name: ionosctl

before:
  hooks:
    - go mod tidy
builds:
  - id: ionosctl
    main: ./main.go
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
      - -mod=vendor
    ldflags:
      - "-X github.com/ionos-cloud/ionosctl/v6/commands.Version={{ .Version }}"
      - "-X github.com/ionos-cloud/ionosctl/v6/commands.Label=release"
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: '{{ .ProjectName }}'

archives:
  - id: ionosctl
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - docs/*
      - LICENSE
      - README.md
      - CHANGELOG.md
    wrap_in_directory: false

scoop:
#  folder: Scoops
  bucket:
    owner: ionos-cloud
    name: scoop-bucket
  homepage: https://github.com/ionos-cloud/ionosctl
  description: IonosCTL is a tool to help you manage your Ionos Cloud resources directly from your terminal.
  license: Apache-2.0

brews:
  - name: ionosctl
    ids:
      - ionosctl
    tap:
      owner: ionos-cloud
      name: homebrew-ionos-cloud
    folder: Formula
    goarm: "7"
    homepage: https://github.com/ionos-cloud/ionosctl
    description: IonosCTL is a tool to help you manage your Ionos Cloud resources directly from your terminal.
    license: Apache-2.0
    dependencies:
      - name: go
        type: optional
    install: |-
      bin.install "ionosctl"

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-SHA256SUMS'
  algorithm: sha256

release:
  prerelease: auto # Mark as not ready for production if rc tag (i.e. v1.0.0-rc.1)
  mode: append
  header: |
    ## [{{ .Tag }}] ({{ .Date }})

# If you want to manually examine the release before its live, uncomment this line:
# draft: true
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^test:'
      - '^dep:'
      - '^deps:'
      - '^dependencies:'
  skip: false
