// Code generated by MockGen. DO NOT EDIT.
// Source: quota.go

// Package mock_resources is a generated GoMock package.
package mock_resources

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	resources "github.com/ionos-cloud/ionosctl/services/cloudapi-dbaas-pgsql/resources"
)

// MockQuotasService is a mock of QuotasService interface.
type MockQuotasService struct {
	ctrl     *gomock.Controller
	recorder *MockQuotasServiceMockRecorder
}

// MockQuotasServiceMockRecorder is the mock recorder for MockQuotasService.
type MockQuotasServiceMockRecorder struct {
	mock *MockQuotasService
}

// NewMockQuotasService creates a new mock instance.
func NewMockQuotasService(ctrl *gomock.Controller) *MockQuotasService {
	mock := &MockQuotasService{ctrl: ctrl}
	mock.recorder = &MockQuotasServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuotasService) EXPECT() *MockQuotasServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockQuotasService) Get() (resources.QuotaList, *resources.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(resources.QuotaList)
	ret1, _ := ret[1].(*resources.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockQuotasServiceMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockQuotasService)(nil).Get))
}
