package dbaas_postgres

const (
	FlagIdShort              = "i"
	FlagStartTime            = "start-time"
	FlagStartTimeShort       = "s"
	FlagEndTime              = "end-time"
	FlagEndTimeShort         = "e"
	FlagSince                = "since"
	FlagSinceShort           = "S"
	FlagUntil                = "until"
	FlagUntilShort           = "U"
	FlagLimit                = "limit"
	FlagLimitShort           = "l"
	FlagDirection            = "direction"
	FlagDirectionShort       = "D"
	FlagVersion              = "version"
	FlagVersionShort         = "V"
	FlagBackupLocation       = "backup-location"
	FlagBackupLocationShort  = "B"
	FlagInstances            = "instances"
	FlagInstancesShort       = "I"
	FlagSyncMode             = "sync"
	FlagSyncModeShort        = "S"
	FlagCores                = "cores"
	FlagRam                  = "ram"
	FlagStorageSize          = "storage-size"
	FlagStorageType          = "storage-type"
	FlagDatacenterId         = "datacenter-id"
	FlagDatacenterIdShort    = "D"
	FlagBackupId             = "backup-id"
	FlagBackupIdShort        = "b"
	FlagRecoveryTime         = "recovery-time"
	FlagRecoveryTimeShort    = "R"
	FlagCidr                 = "cidr"
	FlagCidrShort            = "C"
	FlagLanId                = "lan-id"
	FlagLanIdShort           = "L"
	FlagLocation             = "location-id"
	FlagName                 = "name"
	FlagNameShort            = "n"
	FlagDbUsername           = "db-username"
	FlagDbUsernameShort      = "U"
	FlagDbPassword           = "db-password"
	FlagDbPasswordShort      = "P"
	FlagMaintenanceTime      = "maintenance-time"
	FlagMaintenanceTimeShort = "T"
	FlagMaintenanceDay       = "maintenance-day"
	FlagMaintenanceDayShort  = "d"
	FlagRemoveConnection     = "remove-connection"
)

const (
	ClusterId             = "The unique ID of the Cluster"
	BackupId              = "The unique ID of the Backup"
	DefaultClusterTimeout = int(1200)
)
