package httprule

import (
	"github.com/ionos-cloud/ionosctl/v6/internal/core"
	"github.com/ionos-cloud/ionosctl/v6/internal/printer/table"
	"github.com/ionos-cloud/sdk-go-bundle/shared/fileconfiguration"
	"github.com/spf13/cobra"
)

var allAlbRuleHttpRuleCols = []table.Column{
	{Name: "Name", JSONPath: "name", Default: true},
	{Name: "Type", JSONPath: "type", Default: true},
	{Name: "TargetGroupId", JSONPath: "targetGroup", Default: true},
	{Name: "DropQuery", JSONPath: "dropQuery", Default: true},
	{Name: "Location", JSONPath: "location"},
	{Name: "StatusCode", JSONPath: "statusCode"},
	{Name: "ResponseMessage", JSONPath: "responseMessage"},
	{Name: "ContentType", JSONPath: "contentType"},
	{Name: "Condition", JSONPath: "conditions", Default: true},
}

func AlbRuleHttpRuleCmd() *core.Command {
	albRuleHttpRuleCmd := &core.Command{
		Command: &cobra.Command{
			Use:     "httprule",
			Aliases: []string{"http"},
			Short:   "Application Load Balancer Forwarding Rule Http Rule Operations",
			Long: `HTTP rules live inside a forwarding rule (listener) and define what the balancer does with each incoming HTTP request. A listener holds an ordered list of HTTP rules that are evaluated top to bottom; the first rule whose conditions all match wins. A rule with no conditions always matches, so it makes a good catch-all/default placed last. (Note: within a listener, rules with other action types are evaluated before FORWARD rules.)

Each HTTP rule has one of three action --type values:
  * FORWARD  - proxy the request to a backend target group (--targetgroup-id). This is how traffic actually reaches your servers.
  * REDIRECT - return an HTTP redirect (--status-code 301/302/303/307/308) to --location, optionally dropping the query string (--query).
  * STATIC   - return a fixed response generated by the balancer itself (--status-code, --response-message, --content-type) without touching any backend, e.g. a maintenance page.

Conditions match against a part of the request selected by --condition-type (HEADER, PATH, QUERY, METHOD, HOST, COOKIE, SOURCE_IP), optionally narrowed by --condition-key (e.g. a specific header name), compared using --condition (EQUALS, CONTAINS, MATCHES, STARTS_WITH, ENDS_WITH, EXISTS) against --condition-value, and optionally inverted with --negate.

The sub-commands below let you add, list and remove HTTP rules.`,
			TraverseChildren: true,
		},
	}
	albRuleHttpRuleCmd.AddColsFlag(allAlbRuleHttpRuleCols)

	albRuleHttpRuleCmd.AddCommand(AlbRuleHttpRuleListCmd())
	albRuleHttpRuleCmd.AddCommand(AlbRuleHttpRuleAddCmd())
	albRuleHttpRuleCmd.AddCommand(AlbRuleHttpRuleRemoveCmd())

	return core.WithConfigOverride(albRuleHttpRuleCmd, []string{fileconfiguration.Cloud, "compute"}, "")
}
