// Code generated by MockGen. DO NOT EDIT.
// Source: ./apiversion.go

// Package mock_resources is a generated GoMock package.
package mock_resources

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ionoscloud "github.com/ionos-cloud/sdk-go-dbaas-mongo"
)

// MockApiMetadataService is a mock of ApiMetadataService interface.
type MockApiMetadataService struct {
	ctrl     *gomock.Controller
	recorder *MockApiMetadataServiceMockRecorder
}

// MockApiMetadataServiceMockRecorder is the mock recorder for MockApiMetadataService.
type MockApiMetadataServiceMockRecorder struct {
	mock *MockApiMetadataService
}

// NewMockApiMetadataService creates a new mock instance.
func NewMockApiMetadataService(ctrl *gomock.Controller) *MockApiMetadataService {
	mock := &MockApiMetadataService{ctrl: ctrl}
	mock.recorder = &MockApiMetadataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiMetadataService) EXPECT() *MockApiMetadataServiceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockApiMetadataService) List() ([]ionoscloud.APIVersion, *ionoscloud.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]ionoscloud.APIVersion)
	ret1, _ := ret[1].(*ionoscloud.APIResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockApiMetadataServiceMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockApiMetadataService)(nil).List))
}
