// Code generated by MockGen. DO NOT EDIT.
// Source: ./templates.go

// Package mock_resources is a generated GoMock package.
package mock_resources

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ionoscloud "github.com/ionos-cloud/sdk-go-dbaas-mongo"
)

// MockTemplatesService is a mock of TemplatesService interface.
type MockTemplatesService struct {
	ctrl     *gomock.Controller
	recorder *MockTemplatesServiceMockRecorder
}

// MockTemplatesServiceMockRecorder is the mock recorder for MockTemplatesService.
type MockTemplatesServiceMockRecorder struct {
	mock *MockTemplatesService
}

// NewMockTemplatesService creates a new mock instance.
func NewMockTemplatesService(ctrl *gomock.Controller) *MockTemplatesService {
	mock := &MockTemplatesService{ctrl: ctrl}
	mock.recorder = &MockTemplatesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplatesService) EXPECT() *MockTemplatesServiceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockTemplatesService) List(limit, offset *int32) (ionoscloud.TemplateList, *ionoscloud.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", limit, offset)
	ret0, _ := ret[0].(ionoscloud.TemplateList)
	ret1, _ := ret[1].(*ionoscloud.APIResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTemplatesServiceMockRecorder) List(limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTemplatesService)(nil).List), limit, offset)
}
