package cloudapi_v5

// Resources
const (
	DatacenterResource = "datacenter"
	ServerResource     = "server"
	VolumeResource     = "volume"
	IpBlockResource    = "ipblock"
	SnapshotResource   = "snapshot"
)

// Flags
const (
	ArgAll                   = "all"
	ArgAllShort              = "a"
	ArgUserData              = "user-data"
	ArgFirstName             = "first-name"
	ArgLastName              = "last-name"
	ArgEmail                 = "email"
	ArgEmailShort            = "e"
	ArgPassword              = "password"
	ArgPasswordShort         = "p"
	ArgAdmin                 = "admin"
	ArgName                  = "name"
	ArgNameShort             = "n"
	ArgS3Bucket              = "s3bucket"
	ArgApiSubnets            = "api-subnets"
	ArgDescription           = "description"
	ArgDescriptionShort      = "d"
	ArgLocation              = "location"
	ArgLocationShort         = "l"
	ArgAvailabilityZone      = "availability-zone"
	ArgAvailabilityZoneShort = "z"
	ArgCores                 = "cores"
	ArgRam                   = "ram"
	ArgSize                  = "size"
	ArgSizeShort             = "s"
	ArgBus                   = "bus"
	ArgLicenceType           = "licence-type"
	ArgType                  = "type"
	ArgSshKeyPaths           = "ssh-key-paths"
	ArgSshKeyPathsShort      = "k"
	ArgPublic                = "public"
	ArgPublicShort           = "p"
	ArgIps                   = "ips"
	ArgIp                    = "ip"
	ArgDhcp                  = "dhcp"
	ArgCpuHotPlug            = "cpu-hot-plug"
	ArgCpuHotUnplug          = "cpu-hot-unplug"
	ArgRamHotPlug            = "ram-hot-plug"
	ArgRamHotUnplug          = "ram-hot-unplug"
	ArgNicHotPlug            = "nic-hot-plug"
	ArgNicHotUnplug          = "nic-hot-unplug"
	ArgDiscVirtioHotPlug     = "disc-virtio-hot-plug"
	ArgDiscVirtioHotUnplug   = "disc-virtio-hot-unplug"
	ArgDiscScsiHotPlug       = "disc-scsi-hot-plug"
	ArgDiscScsiHotUnplug     = "disc-scsi-hot-unplug"
	ArgSecAuthProtection     = "sec-auth-protection"
	ArgImageAlias            = "image-alias"
	ArgImageAliasShort       = "a"
	ArgProtocol              = "protocol"
	ArgSourceMac             = "source-mac"
	ArgSourceIp              = "source-ip"
	ArgTargetIp              = "target-ip"
	ArgDestinationIp         = "destination-ip"
	ArgDestinationIpShort    = "D"
	ArgDirection             = "direction"
	ArgDirectionShort        = "d"
	ArgIcmpCode              = "icmp-code"
	ArgIcmpType              = "icmp-type"
	ArgPortRangeStart        = "port-range-start"
	ArgPortRangeStop         = "port-range-end"
	ArgLabelUrn              = "label-urn"
	ArgLabelKey              = "label-key"
	ArgLabelValue            = "label-value"
	ArgResourceLimits        = "resource-limits"
	ArgResourceType          = "resource-type"
	ArgForceSecAuth          = "force-secure-auth"
	ArgCreateDc              = "create-dc"
	ArgCreateSnapshot        = "create-snapshot"
	ArgReserveIp             = "reserve-ip"
	ArgAccessLog             = "access-logs"
	ArgS3Privilege           = "s3privilege"
	ArgCreateBackUpUnit      = "create-backup"
	ArgCreatePcc             = "create-pcc"
	ArgCreateNic             = "create-nic"
	ArgCreateK8s             = "create-k8s"
	ArgEditPrivilege         = "edit-privilege"
	ArgSharePrivilege        = "share-privilege"
	ArgS3KeyActive           = "s3key-active"
	ArgK8sVersion            = "k8s-version"
	ArgK8sNodeCount          = "node-count"
	ArgCpuFamily             = "cpu-family"
	ArgStorageType           = "storage-type"
	ArgStorageSize           = "storage-size"
	ArgK8sMinNodeCount       = "min-node-count"
	ArgK8sMaxNodeCount       = "max-node-count"
	ArgK8sMaintenanceDay     = "maintenance-day"
	ArgK8sMaintenanceTime    = "maintenance-time"
	ArgK8sAnnotationKey      = "annotation-key"
	ArgK8sAnnotationValue    = "annotation-value"
	ArgPublicIps             = "public-ips"
	ArgLatest                = "latest"
	ArgMethod                = "method"
)

// IDs Flags
const (
	ArgIdShort        = "i"
	ArgDataCenterId   = "datacenter-id"
	ArgServerId       = "server-id"
	ArgNicId          = "nic-id"
	ArgLanId          = "lan-id"
	ArgLanIds         = "lan-ids"
	ArgLocationId     = "location-id"
	ArgVolumeId       = "volume-id"
	ArgLoadBalancerId = "loadbalancer-id"
	ArgRequestId      = "request-id"
	ArgSnapshotId     = "snapshot-id"
	ArgImageId        = "image-id"
	ArgIpBlockId      = "ipblock-id"
	ArgFirewallRuleId = "firewallrule-id"
	ArgUserId         = "user-id"
	ArgGroupId        = "group-id"
	ArgResourceId     = "resource-id"
	ArgS3KeyId        = "s3key-id"
	ArgBackupUnitId   = "backupunit-id"
	ArgPccId          = "pcc-id"
	ArgK8sClusterId   = "cluster-id"
	ArgK8sNodePoolId  = "nodepool-id"
	ArgK8sNodeId      = "node-id"
	ArgCdromId        = "cdrom-id"
)

// Descriptions for Flags Resources
const (
	DatacenterId   = "The unique Data Center Id"
	LanId          = "The unique LAN Id"
	LoadBalancerId = "The unique Load Balancer Id"
	NicId          = "The unique NIC Id"
	RequestId      = "The unique Request Id"
	ServerId       = "The unique Server Id"
	VolumeId       = "The unique Volume Id"
	SnapshotId     = "The unique Snapshot Id"
	ImageId        = "The unique Image Id"
	IpBlockId      = "The unique IpBlock Id"
	FirewallRuleId = "The unique FirewallRule Id"
	LocationId     = "The unique Location Id"
	LabelKey       = "The unique Label Key"
	LabelValue     = "The unique Label Value"
	UserId         = "The unique User Id"
	GroupId        = "The unique Group Id"
	ResourceId     = "The unique Resource Id"
	S3KeyId        = "The unique User S3Key Id"
	BackupUnitId   = "The unique BackupUnit Id"
	PccId          = "The unique Private Cross-Connect Id"
	K8sClusterId   = "The unique K8s Cluster Id"
	K8sNodePoolId  = "The unique K8s Node Pool Id"
	K8sNodeId      = "The unique K8s Node Id"
	CdromId        = "The unique Cdrom Id"
)

// Default values
const (
	DefaultPublic          = false
	DefaultDhcp            = true
	K8sTimeoutSeconds      = int(600)
	DefaultServerCores     = 2
	DefaultVolumeSize      = 10
	DefaultNicLanId        = 1
	DefaultServerCPUFamily = "AMD_OPTERON"
)
