// Code generated by MockGen. DO NOT EDIT.
// Source: datacenter.go

// Package mock_v5 is a generated GoMock package.
package mock_v5

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v5 "github.com/ionos-cloud/ionosctl/pkg/resources/v5"
)

// MockDatacentersService is a mock of DatacentersService interface.
type MockDatacentersService struct {
	ctrl     *gomock.Controller
	recorder *MockDatacentersServiceMockRecorder
}

// MockDatacentersServiceMockRecorder is the mock recorder for MockDatacentersService.
type MockDatacentersServiceMockRecorder struct {
	mock *MockDatacentersService
}

// NewMockDatacentersService creates a new mock instance.
func NewMockDatacentersService(ctrl *gomock.Controller) *MockDatacentersService {
	mock := &MockDatacentersService{ctrl: ctrl}
	mock.recorder = &MockDatacentersServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatacentersService) EXPECT() *MockDatacentersServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDatacentersService) Create(name, description, region string) (*v5.Datacenter, *v5.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name, description, region)
	ret0, _ := ret[0].(*v5.Datacenter)
	ret1, _ := ret[1].(*v5.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *MockDatacentersServiceMockRecorder) Create(name, description, region interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDatacentersService)(nil).Create), name, description, region)
}

// Delete mocks base method.
func (m *MockDatacentersService) Delete(datacenterId string) (*v5.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", datacenterId)
	ret0, _ := ret[0].(*v5.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDatacentersServiceMockRecorder) Delete(datacenterId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDatacentersService)(nil).Delete), datacenterId)
}

// Get mocks base method.
func (m *MockDatacentersService) Get(datacenterId string) (*v5.Datacenter, *v5.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", datacenterId)
	ret0, _ := ret[0].(*v5.Datacenter)
	ret1, _ := ret[1].(*v5.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockDatacentersServiceMockRecorder) Get(datacenterId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDatacentersService)(nil).Get), datacenterId)
}

// List mocks base method.
func (m *MockDatacentersService) List() (v5.Datacenters, *v5.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].(v5.Datacenters)
	ret1, _ := ret[1].(*v5.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockDatacentersServiceMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDatacentersService)(nil).List))
}

// Update mocks base method.
func (m *MockDatacentersService) Update(datacenterId string, input v5.DatacenterProperties) (*v5.Datacenter, *v5.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", datacenterId, input)
	ret0, _ := ret[0].(*v5.Datacenter)
	ret1, _ := ret[1].(*v5.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Update indicates an expected call of Update.
func (mr *MockDatacentersServiceMockRecorder) Update(datacenterId, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDatacentersService)(nil).Update), datacenterId, input)
}
