// Code generated by MockGen. DO NOT EDIT.
// Source: ipblock.go

// Package mock_resources is a generated GoMock package.
package mock_resources

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	resources "github.com/ionos-cloud/ionosctl/services/cloudapi-v6/resources"
)

// MockIpBlocksService is a mock of IpBlocksService interface.
type MockIpBlocksService struct {
	ctrl     *gomock.Controller
	recorder *MockIpBlocksServiceMockRecorder
}

// MockIpBlocksServiceMockRecorder is the mock recorder for MockIpBlocksService.
type MockIpBlocksServiceMockRecorder struct {
	mock *MockIpBlocksService
}

// NewMockIpBlocksService creates a new mock instance.
func NewMockIpBlocksService(ctrl *gomock.Controller) *MockIpBlocksService {
	mock := &MockIpBlocksService{ctrl: ctrl}
	mock.recorder = &MockIpBlocksServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIpBlocksService) EXPECT() *MockIpBlocksServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIpBlocksService) Create(name, location string, size int32, params resources.QueryParams) (*resources.IpBlock, *resources.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name, location, size, params)
	ret0, _ := ret[0].(*resources.IpBlock)
	ret1, _ := ret[1].(*resources.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *MockIpBlocksServiceMockRecorder) Create(name, location, size, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIpBlocksService)(nil).Create), name, location, size, params)
}

// Delete mocks base method.
func (m *MockIpBlocksService) Delete(ipBlockId string, params resources.QueryParams) (*resources.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ipBlockId, params)
	ret0, _ := ret[0].(*resources.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIpBlocksServiceMockRecorder) Delete(ipBlockId, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIpBlocksService)(nil).Delete), ipBlockId, params)
}

// Get mocks base method.
func (m *MockIpBlocksService) Get(IpBlockId string, params resources.QueryParams) (*resources.IpBlock, *resources.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", IpBlockId, params)
	ret0, _ := ret[0].(*resources.IpBlock)
	ret1, _ := ret[1].(*resources.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockIpBlocksServiceMockRecorder) Get(IpBlockId, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIpBlocksService)(nil).Get), IpBlockId, params)
}

// List mocks base method.
func (m *MockIpBlocksService) List(params resources.ListQueryParams) (resources.IpBlocks, *resources.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", params)
	ret0, _ := ret[0].(resources.IpBlocks)
	ret1, _ := ret[1].(*resources.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockIpBlocksServiceMockRecorder) List(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIpBlocksService)(nil).List), params)
}

// Update mocks base method.
func (m *MockIpBlocksService) Update(ipBlockId string, input resources.IpBlockProperties, params resources.QueryParams) (*resources.IpBlock, *resources.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ipBlockId, input, params)
	ret0, _ := ret[0].(*resources.IpBlock)
	ret1, _ := ret[1].(*resources.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Update indicates an expected call of Update.
func (mr *MockIpBlocksServiceMockRecorder) Update(ipBlockId, input, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIpBlocksService)(nil).Update), ipBlockId, input, params)
}
