name: ionosctl # registered name
summary: IONOS Cloud CLI tool.
base: core20
description: |
  The IONOS Cloud CLI (ionosctl) gives the ability to manage IONOS Cloud infrastructure directly from Command Line.

adopt-info: ionosctl
grade: stable
confinement: strict
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
apps:
  ionosctl:
    command: bin/ionosctl
    plugs:
      - home
      - network
      - removable-media

parts:
  ionosctl:
    plugin: nil
    source: https://github.com/ionos-cloud/ionosctl.git
    source-type: git
    override-pull: |
      git clone https://github.com/ionos-cloud/ionosctl.git src/github.com/ionos-cloud/ionosctl
       cd src/github.com/ionos-cloud/ionosctl
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
    override-build: |
      export GOPATH=$PWD
      cd src/github.com/ionos-cloud/ionosctl
      
      case "$SNAPCRAFT_ARCH_TRIPLET" in
        "x86_64-linux-gnu") GOARCH=amd64 ;;
        "arm-linux-gnueabihf") GOARCH=arm ;;
        "aarch64-linux-gnu") GOARCH=arm64 ;;
        "i386-linux-gnu") GOARCH=386 ;;
        *) echo "Unsupported architecture: $SNAPCRAFT_ARCH_TRIPLET" && exit 1 ;;
      esac
      
      OUT_D=$SNAPCRAFT_PART_INSTALL/bin GOARCH=$GOARCH GOOS=linux SIMPLE_NAME=true tools/build.sh build
    build-snaps:
    - go
    build-packages:
    - git
    - sed
