// Code generated by MockGen. DO NOT EDIT.
// Source: info.go

// Package mock_resources is a generated GoMock package.
package mock_resources

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	resources "github.com/ionos-cloud/ionosctl/services/dbaas-pg/resources"
)

// MockInfosService is a mock of InfosService interface.
type MockInfosService struct {
	ctrl     *gomock.Controller
	recorder *MockInfosServiceMockRecorder
}

// MockInfosServiceMockRecorder is the mock recorder for MockInfosService.
type MockInfosServiceMockRecorder struct {
	mock *MockInfosService
}

// NewMockInfosService creates a new mock instance.
func NewMockInfosService(ctrl *gomock.Controller) *MockInfosService {
	mock := &MockInfosService{ctrl: ctrl}
	mock.recorder = &MockInfosServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInfosService) EXPECT() *MockInfosServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockInfosService) Get() (resources.APIVersion, *resources.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(resources.APIVersion)
	ret1, _ := ret[1].(*resources.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockInfosServiceMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInfosService)(nil).Get))
}

// List mocks base method.
func (m *MockInfosService) List() (resources.APIVersionList, *resources.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].(resources.APIVersionList)
	ret1, _ := ret[1].(*resources.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockInfosServiceMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInfosService)(nil).List))
}
