name: CI-Weekly

on:
  schedule:
  - cron: "15 7 * * 1"

jobs:
  test:
    name: Test ionosctl
    env:
      package-name: ionoscloud
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go-version: [ 1.14, 1.15, 1.16 ]
    runs-on: ${{ matrix.os }}
    outputs:
      go-version: ${{ matrix.go-version }}
      package-name: ${{ env.package-name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check code format
        run: make gofmt_check
        if: matrix.os == 'ubuntu-latest'
      - name: Run tests
        run: make test
      - name: Build
        run: make build
      - name: Install
        run: make install
      - name: Version
        run: ionosctl version
      - name: Clean artifacts
        run: make clean
