package token

import (
	"context"

	"github.com/ionos-cloud/ionosctl/v6/internal/client"
	"github.com/ionos-cloud/ionosctl/v6/internal/constants"
	"github.com/ionos-cloud/ionosctl/v6/internal/core"
	"github.com/spf13/viper"
)

func TokenListCmd() *core.Command {
	cmd := core.NewCommand(context.Background(), nil, core.CommandBuilder{
		Namespace:  "token",
		Resource:   "token",
		Verb:       "list",
		Aliases:    []string{"l", "ls"},
		ShortDesc:  "List Tokens",
		LongDesc:   "Use this command to retrieve a complete list of Tokens under your account, to list the details of all tokens, generated by the user.",
		Example:    listTokenExample,
		PreCmdRun:  core.NoPreRun,
		CmdRun:     runTokenList,
		InitClient: true,
	})
	cmd.AddIntFlag(constants.FlagContract, "", 0, "Users with multiple contracts must provide the contract number, for which the tokens are listed")

	return cmd
}

func runTokenList(c *core.CommandConfig) error {
	if viper.IsSet(core.GetFlagName(c.NS, constants.FlagContract)) {
		c.Verbose(contractNumberMessage, viper.GetInt32(core.GetFlagName(c.NS, constants.FlagContract)))
	}

	req := client.Must().AuthClient.TokensApi.TokensGet(context.Background())

	if viper.GetInt32(core.GetFlagName(c.NS, constants.FlagContract)) != 0 {
		req = req.XContractNumber(viper.GetInt32(core.GetFlagName(c.NS, constants.FlagContract)))
	}

	tokens, _, err := req.Execute()
	if err != nil {
		return err
	}

	return c.Printer(allTokenCols).Print(tokens.Tokens)
}
